### ISSUE TITLE
Can't join server

### ISSUE THREAD

**Issue by CodeYimin** [ZengineeringTeam/Zengineering#32]
Internal Exception: io.netty.handler.codec.DecoderException:
java.lang.IndexOutOfBoundsException: Index: 25, Size: 5

![image](https://user-images.githubusercontent.com/56568926/124399212-089d9300-dce8-11eb-866c-8ce8c4a60d29.png)

**Comment by Eldritch-Oliver** [comment]
Hi there,

I am also experiencing this error, I have built the server from both the client modpack profile and the server files provided on CurseForge to no avail.

---

## Server Specifications:
 - Allocated RAM: 10 GB
 - RAM Used when Connecting: ~5,700 MB
 - Operating System: Ubuntu 18.04 LTS
 - Modpack Version: 2.2.1

---

## Client Specifications:
 - Allocated RAM: 5 GB
 - RAM Used by Minecraft when Connecting: 3.4 GiB
 - Total RAM usage when Connecting: 8.8 GB
 - Operating System: Ubuntu 20.04 LTS
 - Modpack Version: 2.2.1

---

When building from the client profile the Discord RPC and `eguilib` mods had to be disabled, as expected.

**Comment by Snownee** [comment]
I hope I have fixed it in 2.2.3

**Comment by NotGeri** [comment]
It's not, but if anyone else is having issues, remove the ReAuth mod from the server's `mods/` folder (`ReAuth-1.16-Forge-3.9.3.jar` currently)

📝**Edit**: No, I was wrong. If you simply restart the server one more time, it'll work just fine, however, the root cause seems to be due to the ServerconfigUpdater, or rather something that hooks into it. I don't have the patience to check which one of the 70+ mods is doing it but just in case someone else is having this issue, I'd start there.
